### ISSUE TITLE
Vendor folder missing

### ISSUE THREAD

**Issue by shashankbhuvanala** [KsCorrales/laravel-firebase-chat#1]
> C:\laravel-firebase-chat>php artisan serve
PHP Warning:  require(C:\laravel-firebase-chat\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\laravel-firebase-chat\bootstrap\autoload.php on line 17

> Warning: require(C:\laravel-firebase-chat\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\laravel-firebase-chat\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\laravel-firebase-chat\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\laravel-firebase-chat\bootstrap\autoload.php on line 17

> Fatal error: require(): Failed opening required 'C:\laravel-firebase-chat\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\laravel-firebase-chat\bootstrap\autoload.php on line 17

Returns above errors when am serving artisan serve in my local
Not able to find vendors directory in root folder after git clone

**Comment by KsCorrales** [comment]
you have to run composer install after git clone.
